### ISSUE TITLE
accept constraints list as input

### ISSUE THREAD

**Issue by dhellmann** [python-wheel-build/fromager#102]
There may be situations where fromager should constrain the versions of packages it builds beyond what the original requirements specifications say. For example, if someone wants to distribute a set of packages and exclude one version of one package with a known issue, it would be useful to be able to express that somehow to the resolver.

If we change a requirement specification based on a constraint, we should log that at INFO level.

We should think about whether we need to enforce a constraint fitting within the requested range. For example, if someone asks for `torch>=2.3.0,<2.4.0`, should it be valid to have a constraint `torch==2.5.0`? We could build that, but then it wouldn't be usable for the installation.

We may also need to support markers in constraints so that we can have different constraints for different platforms or python versions. We have [a function](https://github.com/python-wheel-build/fromager/blob/main/src/fromager/dependencies.py#L217) to evaluate a marker expression.

Another case to consider is whether a constraint adds a cap or exclusion that is not present in the original requirement, but does not actually specify a particular version to use. If a requirement is `torch>=2.3.0` and the constraint adds `torch!=2.3.1,<2.4.0`, we could merge those settings into the existing requirement. We might consider that as a separate ticket, though, since the logic might be complex. Perhaps pip or resolvelib has something we can reuse, though?

Tasks:

- [x] Implement a simple constraints lists that only accepts `==` #144 
- [x] Add support for `<` #166

**Comment by shubhbapna** [comment]
Should we add an `version_constraint` field in settings? So maybe something like:

```yaml
version_constraint:
  cuda:
     - torch==2.3.0
     - numpy<2.0.0
```

And then in the resolvers we can probably do the constraint check here:
- https://github.com/python-wheel-build/fromager/blob/main/src/fromager/resolver.py#L228
- https://github.com/python-wheel-build/fromager/blob/main/src/fromager/resolver.py#L297

**Comment by dhellmann** [comment]
It would probably be most convenient to pass a constraints.txt file, instead of adding that info to the settings file. Lots of tools in the python ecosystem can produce constraints files.

I think we only need constraints for bootstrapping, since everything else already operates on an exact version of a package.

Fromager only works on one variant at a time, so I think we'd only need one constraints file at a time (the caller might have different constraints for different variants, but they can keep them in separate files).

**Comment by dhellmann** [comment]
As far as what constraints we allow, we could start simple and just support exact versions using `==`. Later we could make it more complex, supporting ranges or exclusions. That would require modifying the resolver code, though, and I'm wary of making changes there right now.

**Comment by shubhbapna** [comment]
So we would provide a constraints file via cli options to fromager when bootstrapping. Will fromager then enforce those constraints when it is about to download the sdists of the package? Won't this still require modifying the resolver code even just for `==`?

**Comment by dhellmann** [comment]
Right, the idea is that fromager would change the requirement based on constraints it enforces so the resolver only ever sees the constrained requirements.

If the resolver code accepts constraints, we could pass them in to that layer for handling, too, I guess, but I had intended to do it in fromager so we could log that we were overriding a requirement with a constraint.

**Comment by shubhbapna** [comment]
Oh got it I think I understand what you mean. What do you think if we enforce the constraints check here then:
https://github.com/python-wheel-build/fromager/blob/main/src/fromager/dependencies.py#L34

**Comment by dhellmann** [comment]
> Oh got it I think I understand what you mean. What do you think if we enforce the constraints check here then: https://github.com/python-wheel-build/fromager/blob/main/src/fromager/dependencies.py#L34

That's definitely a candidate spot. It doesn't already have access to the WorkContext, though. How hard would it be to update all of the functions that need to pass that extra value in?

Another place to do it is in the bootstrap logic, right before resolving a dependency. There we would replace `req` with a new value based on the constraint. One benefit of doing it there is that it's explicitly limited to handling dependencies of the bootstrap process. It also lets us log that we're changing the dependency.

**Comment by dhellmann** [comment]
I didn't leave very detailed notes when I originally opened this ticket, so I've tried to expand the description with more information.

**Comment by shubhbapna** [comment]
> Another place to do it is in the bootstrap logic, [right before resolving a dependency](https://github.com/python-wheel-build/fromager/blob/main/src/fromager/sdist.py#L79-L82). There we would replace `req` with a new value based on the constraint. One benefit of doing it there is that it's explicitly limited to handling dependencies of the bootstrap process. It also lets us log that we're changing the dependency.

Got it, this makes sense

**Comment by shubhbapna** [comment]
> We should think about whether we need to enforce a constraint fitting within the requested range. For example, if someone asks for `torch>=2.3.0,<2.4.0`, should it be valid to have a constraint `torch==2.5.0`? We could build that, but then it wouldn't be usable for the installation.

For this I think we could do what pip does and just raise an error informing the user of a conflict?

**Comment by dhellmann** [comment]
> > We should think about whether we need to enforce a constraint fitting within the requested range. For example, if someone asks for `torch>=2.3.0,<2.4.0`, should it be valid to have a constraint `torch==2.5.0`? We could build that, but then it wouldn't be usable for the installation.
> 
> For this I think we could do what pip does and just raise an error informing the user of a conflict?

Yes, that makes sense.

**Comment by dhellmann** [comment]
I added another requirement about merging expressions to the description.

**Comment by shubhbapna** [comment]
> Another case to consider is whether a constraint adds a cap or exclusion that is not present in the original requirement, but does not actually specify a particular version to use. If a requirement is `torch>=2.3.0` and the constraint adds `torch!=2.3.1,<2.4.0`, we could merge those settings into the existing requirement. We might consider that as a separate ticket, though, since the logic might be complex. Perhaps pip or resolvelib has something we can reuse, though?

i was going through the pip repository to see how they handle conflicts. it seems like they are not simplifying the combined constraint and original requirement to detect conflicts before hand. instead, when they are finding the candidate to install they check if that candidate satisfies the constraint as well:
https://github.com/pypa/pip/blob/main/src/pip/_internal/resolution/resolvelib/factory.py#L463
From what I can find there doesn't seem to be a straightforward way to simplify constraint and original requirement or see if they are mutually exclusive:
https://github.com/pypa/packaging/issues/762
https://github.com/pypa/packaging/issues/776
So, i think we might have to stick to the implementation where I had applied the "and"  operation and essentially check all the possible candidates against the new combined requirement. If no candidate is found then we raise a conflict error if a constraint was specified.

**Comment by shubhbapna** [comment]
> We should think about whether we need to enforce a constraint fitting within the requested range. For example, if someone asks for `torch>=2.3.0,<2.4.0`, should it be valid to have a constraint `torch==2.5.0`? We could build that, but then it wouldn't be usable for the installation.

Turns out we can't raise an error. There already some packages which a conflicting dependency requirements, i.e. there is particular version of that dependency that satisfies all of the packages that depend on it. So a better approach might be to ignore the constraint if there is no version that matches both the requirement and the constraint

**Comment by shubhbapna** [comment]
For now we will keep the current basic implementation using `==` since it is meeting our requirements and so there is no need to make it more complex. If we do need to implement the full functionality then in my opinion this should be our approach:
- Pass the `Constraint` object to the `Provider` to implement candidate filtering
- If a candidate matches its constraint and requirement then select it
- If there is no candidate that matches both the constraint and requirement then somehow the resolver should select the candidate that matches the requirement
- We shouldn't raise an error when there is a conflict between a constraint and requirement. The constraint should be ignored

**Comment by shubhbapna** [comment]
Marking this as closed since all the main features have been implemented
