### ISSUE TITLE
pass environment variables from caller to build steps

### ISSUE THREAD

**Issue by prarit** [python-wheel-build/fromager#115]
Is it possible to have fromager pass the value of MAX_JOBS into build processes?  This would be great for systems with a lot of cpus and memory.

**Comment by dhellmann** [comment]
How would fromager know the right value?

Is that variable globally understood, or is it something specific to a package or tool?

**Comment by prarit** [comment]
IIUC, ninja provides a MAX_JOBS environment variable that is used in, for example, -j with cmake and make.

For example, in runs of builder I see:

```
  Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
```

Unfortunately, setting MAX_JOBS in the environment is not honored by fromager, or at least attempting to set it globally doesn't appear to work.

This isn't about fromager setting the value, rather that it passes that value on.
