### ISSUE TITLE
add credentials for GitHub resolver

### ISSUE THREAD

**Issue by dhellmann** [python-wheel-build/fromager#118]
GitHub has rate limiting for anon access based on IP addresses. Is there a way to pass credentials in case our infra runs into rate limiting?

_Originally posted by @tiran in https://github.com/python-wheel-build/fromager/pull/105#discussion_r1661402646_

**Comment by shubhbapna** [comment]
Is just checking if GITHUB_TOKEN env variable is defined enough or should we also add an option of passing the token via a command line option such as `--gh-token`

**Comment by dhellmann** [comment]
> Is just checking if GITHUB_TOKEN env variable is defined enough or should we also add an option of passing the token via a command line option such as `--gh-token` @dhellmann

We've avoided having to add any auth arguments so far, let's see if we can keep that going and rely on the GITHUB_TOKEN variable. It should be optional, but if it's set to a non-empty value then the client should use it for authentication.
