### ISSUE TITLE
highlight duplicates when writing the constraints file

### ISSUE THREAD

**Issue by dhellmann** [python-wheel-build/fromager#151]
One of the outputs from bootstrapping is a constraints.txt file that can be used with pip to control the versions of packages that are installed, so they match the versions that will be built by the build order file.

Unfortunately, in some complex dependency trees there are duplicate requirements for the same package that end up being evaluated differently and producing conflicts in that constraints file.

We should ensure that any duplicates are listed at a the top of the file. We should pick a version for the real constraint, and include commented values for the other constraints.

**Comment by rd4398** [comment]
Does duplicates mean requirement name duplicate with different version? Example: Will the following be considered duplicate?
flit-core==3.9.0
wheel==0.43.0
flit-core==3.11.0
wheel==0.44.0

**Comment by dhellmann** [comment]
Yes, that's right.

**Comment by rd4398** [comment]
Okay, I plan to solve this by processing list of requirements from constraints.txt and writing to a temp file. Then renaming the temp file to constraints.txt and deleting the old constraints.txt. Does that make sense? 

Also, is `We should pick a version for the real constraint, and include commented values for the other constraints.` a manual process or should code do it?

**Comment by dhellmann** [comment]
The constraints file that needs to be updated is the one generated by fromager as it runs the bootstrap process. That code is [here](https://github.com/python-wheel-build/fromager/blob/main/src/fromager/context.py#L121). The file is re-written every time that function is called, so you shouldn't need a temporary file. Just update the way it's output there.

**Comment by dhellmann** [comment]
> Also, is `We should pick a version for the real constraint, and include commented values for the other constraints.` a manual process or should code do it?

That's a good question. Maybe we don't pick for now, and just list the ones with duplicates at the top of the file so it's easy for a person to pick them.

**Comment by rd4398** [comment]
okay, will do!
