### ISSUE TITLE
empty e2e target in tox.ini

### ISSUE THREAD

**Issue by shubhbapna** [python-wheel-build/fromager#157]
Running `tox -e e2e` throws an error. The e2e target doesn't seem to do anything: 
https://github.com/python-wheel-build/fromager/blob/main/tox.ini#L42C1-L43C9

(cc @rd4398)

**Comment by dhellmann** [comment]
That environment is used from the scripts in the e2e directory to have an easy way to create a virtualenv in CI. The script builds the environment, then activates it and uses the contents.

**Comment by rd4398** [comment]
oh okay, got it!
