### ISSUE TITLE
add support for more expressions in constraints files

### ISSUE THREAD

**Issue by dhellmann** [python-wheel-build/fromager#166]
We have cases where we want to cap but not pin requirements. We need support for constraint expressions other than `==`.

**Comment by dhellmann** [comment]
@shubhbapna when you looked at the pip source, you found that it was just applying the requirement and then also the constraint when doing the resolution. Maybe we can take the same approach? I feel like that was going to involve touching a lot of code, though. Let me know what you think the best approach is.

**Comment by shubhbapna** [comment]
That will most likely involve messing with the resolver code. Will that be okay?

**Comment by dhellmann** [comment]
> That will most likely involve messing with the resolver code. Will that be okay?

It's not ideal, but may be necessary. We should map out what would have to change before making any changes, to see if we can come up with alternatives.

**Comment by shubhbapna** [comment]
This is the plan I had come up with from our discussion from before:

- Pass the Constraint object to the Provider to implement candidate filtering
- If a candidate matches its constraint and requirement then select it. Will need to add an if statement to `find_matches` and `is_satisfied_by` for each provider

Optionally, not required for now:

- If there is no candidate that matches both the constraint and requirement then somehow the resolver should select the candidate that matches the requirement
- We shouldn't raise an error when there is a conflict between a constraint and requirement. The constraint should be ignored

**Comment by dhellmann** [comment]
> This is the plan I had come up with from our discussion from before:
> 
> * Pass the Constraint object to the Provider to implement candidate filtering
> * If a candidate matches its constraint and requirement then select it. Will need to add an if statement to `find_matches` and `is_satisfied_by` for each provider

OK, that seems like a good approach.

> 
> Optionally, not required for now:
> 
> * If there is no candidate that matches both the constraint and requirement then somehow the resolver should select the candidate that matches the requirement
> * We shouldn't raise an error when there is a conflict between a constraint and requirement. The constraint should be ignored

I'm not sure about these requirements. I guess it would mean we could at least get _something_ but then if that's the wrong thing we may not want to use it.

Another aspect to consider might be that we apply the constraints only to some "types" of requirements (we can tell if a requirement is an installation dependency or a build dependency, for example). By default we could constrain all the time, but maybe the user could provide an option to indicate that constraints should only apply to installation dependencies.

We want to balance being able to use constraints, which are applied broadly, with having to write patches to change dependency settings on projects, which requires a lot more manual work. The ability to write a patch means we don't have to make fromager's constraint handling perfect.

**Comment by dhellmann** [comment]
You're right, I forgot we'd talked about the consistency angle. I should have written that down.

I think it's probably better to fail if we're given inputs we can't handle than it is to try to guess that it's OK to build something that doesn't match the constraint. Users might have to do something to work around the issue, but there are several approaches to doing that.
