### ISSUE TITLE
optimize sdist production during bootstrapping

### ISSUE THREAD

**Issue by dhellmann** [python-wheel-build/fromager#168]
During bootstrapping we always prepare source and build an sdist, but we avoid rebuilding a wheel if it already exists. We could do the same thing with sdists, so that if one exists in the build directory we would not build it again.

**Comment by rd4398** [comment]
I can see that there is a method called `find_sdist()` in `finders.py line 24`. This method checks if sdist is present in `sdist-repo/downloads` and returns it if present. I can also see `find_wheel()` being used in `sdist.py line 181` which does similar thing. Thus:

- Can we use the already existing `find_sdist()` method to check whether sdist already exists and use it to avoid download again? 
- If not, should we create another method which checks whether sdist is in `sdist-repo/builds` directory and then download if it does not exist. (This method will be similar to `find_sdist()` except change is search location)
- The existence of sdist will be checked in `sources.py before line 128` 

Does it make sense? I am not sure

**Comment by dhellmann** [comment]
We should already be skipping redownloading an sdist if we have a copy. This ticket is about avoiding _building_ a new sdist from the modified sources if we have done that.

https://github.com/python-wheel-build/fromager/blob/main/src/fromager/sdist.py#L198 is the call that builds the source distribution that includes any patches we apply. It writes that output to a different directory from the original source that we downloaded.

You're right that doing something like calling `find_sdist()` before that build step should be what we need. It looks like you can pass the directory to it, so we can pass the builds directory instead of the downloads directory. We'll want to do that before line 198 in sdist.py, though.

**Comment by rd4398** [comment]
okay, will take a look
Thanks

**Comment by rd4398** [comment]
https://github.com/python-wheel-build/fromager/blob/main/src/fromager/sdist.py#L198 this call returns `sdist_filename` but I don't see the return value used anywhere later in the code. Am I missing something?

**Comment by dhellmann** [comment]
> https://github.com/python-wheel-build/fromager/blob/main/src/fromager/sdist.py#L198 this call returns `sdist_filename` but I don't see the return value used anywhere later in the code. Am I missing something?

That function is also used in one of the `step` commands to just produce the source distribution. The step commands print the name of the artifact they produce so that a shell script that is calling them can find the newly created artifact.
