### ISSUE TITLE
include constraint info in comments in generated constraints.txt

### ISSUE THREAD

**Issue by dhellmann** [python-wheel-build/fromager#213]
The constraints.txt file we produce includes comments about what depends on each package. It should also include constraint details that feed into fromager so a reader can understand if the original requirements were modified.

**Comment by rd4398** [comment]
Can you please give an example of constraint info that should be included?

**Comment by dhellmann** [comment]
One of the inputs to the bootstrap process is a constraints file that looks just like a requirements file. If we have one, the bootstrap process uses a [Constraints instance](https://github.com/python-wheel-build/fromager/blob/main/src/fromager/constraints.py#L15) to look up whether a package has a constraint. That information is then included when the package is [added to the build order](https://github.com/python-wheel-build/fromager/blob/main/src/fromager/context.py#L92).

The comment should include the contents of the "constraint" field in that build order entry.
