### ISSUE TITLE
Feature: Create overrides/patches/<package> directories

### ISSUE THREAD

**Issue by prarit** [python-wheel-build/fromager#230]
The overrides/patches directory contains patches that are applied to specific versions of packages.  For example, there exists a torch-2.3.0 and a torch-2.3.1.  This directory layout requires a new package-version directory be created every time the package is updated.  In many cases the patches may be simply updated and copied from one package-version directory to the next, and in some cases new patches are required.

In most cases the patches, can be simply copied from one directory to the next -- that is, there isn't any reason for a new package-version directory to be created.  We could simply create a general package directory, with patches, that could be applied to top-of-tree and only create a package-version directory if the patches changed.

This would minimize efforts when packages are updated.

**Comment by shubhbapna** [comment]
Should we also consider the case where we need to apply a general package patch and a version specific patch? In this case would we apply patches from both the directories?

Another case to consider would be what if there is a particular version for which the general package patches are not applicable anymore?

**Comment by dhellmann** [comment]
> Should we also consider the case where we need to apply a general package patch and a version specific patch? In this case would we apply patches from both the directories?

Yes, that makes some sense. I think I'd apply the unversioned patches first and then the version-specific ones.

> Another case to consider would be what if there is a particular version for which the general package patches are not applicable anymore?

I think I'd rely on the user to remove any useless patches. If they have to build an old and new version, and the patches are different, then that's what the version directories are for.

**Comment by shubhbapna** [comment]
> I think I'd rely on the user to remove any useless patches. If they have to build an old and new version, and the patches are different, then that's what the version directories are for.

Right but if we are applying both unversioned patches and the version specific ones then it might cause a problem. Say for some package we can apply the unversioned patch to version 1.1.0 and 1.2.0 but we cannot apply the same patch to version 2.0.0. How would we express that?

**Comment by dhellmann** [comment]
> > I think I'd rely on the user to remove any useless patches. If they have to build an old and new version, and the patches are different, then that's what the version directories are for.
> 
> Right but if we are applying both unversioned patches and the version specific ones then it might cause a problem. Say for some package we can apply the unversioned patch to version 1.1.0 and 1.2.0 but we cannot apply the same patch to version 2.0.0. How would we express that?

If the patches can't apply cleanly regardless of the version, then they aren't version-less patches. The user would have to put them in a version directory.

**Comment by shubhbapna** [comment]
> If the patches can't apply cleanly regardless of the version, then they aren't version-less patches. The user would have to put them in a version directory.

That would result in having no version-less patches at all. So even though version 1.1.0 and 1.2.0 can work with the same patch because of version 2.0.0, the user will need to have a version specific patch directory for 1.1.0 and 1.2.0 correct?

**Comment by dhellmann** [comment]
> > If the patches can't apply cleanly regardless of the version, then they aren't version-less patches. The user would have to put them in a version directory.
> 
> That would result in having no version-less patches at all. So even though version 1.1.0 and 1.2.0 can work with the same patch because of version 2.0.0, the user will need to have a version specific patch directory for 1.1.0, 1.2.0 and 2.0.0 correct?

Yes, that's right. I think that's accurate, though, right? We could get really complex about having them express version ranges that do or don't work with specific patches. But I expect most users to update to new versions of dependencies and stop needing the old ones, over time. So I could see them either fixing the patches to work with 2.x and no longer building 1.x, or making separate copies of the patches until they can do that.

**Comment by shubhbapna** [comment]
How would the warnings work? https://github.com/python-wheel-build/fromager/blob/main/src/fromager/sources.py#L280

Should we still warn if unversioned patches are being applied?

**Comment by dhellmann** [comment]
> How would the warnings work? https://github.com/python-wheel-build/fromager/blob/main/src/fromager/sources.py#L280
> 
> Should we still warn if unversioned patches are being applied?

Yeah, I think we should keep that. Regardless of what patches we do apply, we should warn if there are other patches that are not being applied.
