### ISSUE TITLE
configuration option for build dir relative to source root

### ISSUE THREAD

**Issue by dhellmann** [python-wheel-build/fromager#278]
Downstream we have several packages that unpack a source archive and then need to build in a subdirectory of that. It would be convenient to have a configuration option for that.

**Comment by shubhbapna** [comment]
There seems to be a lot of places where this directory might be needed:
- `get_build_system_dependencies`
- `get_build_backend_dependencies`
- `get_build_sdist_dependencies`
- `build_sdist`
- `build_wheel`

Can you confirm if one field in the settings is enough and can be used for all these functions @dhellmann ?

**Comment by dhellmann** [comment]
Yes, I think we would be safe with 1 path. The idea is to say that all of the steps that normally use the root of the unpacked source dist should instead use a subdirectory within that directory.
