### ISSUE TITLE
fromager does not handle packages with hyphens in their name

### ISSUE THREAD

**Issue by prarit** [python-wheel-build/fromager#281]
[To be clear, I'm not sure there's anything that can be done for a package that violates the python package naming spec.  I'm reporting this more to determine if there's a workaround.]

When executing builder's "bootstrap.sh Container.cuda-ubi9 nvidia-cutlass", with the following package_plugin:
```

import logging
import pathlib
import shutil

from fromager import context, dependencies, sources, wheels
from packaging.requirements import Requirement
from packaging.version import Version

logger = logging.getLogger(__name__)

version = "3.5.0"

def download_source(ctx, req, sdist_server_url):
    logger.info("Overriding pypi lookup for nvidia-cutlass.")

    source_filename = sources.download_url(
        ctx.sdists_downloads,
        _get_triton_release_tarball_url(version),
    )
    return source_filename, version


def _get_triton_release_tarball_url(version):
    return f"https://github.com/NVIDIA/cutlass/archive/refs/tags/v{version}.tar.gz"
```

builder will fail with:

Processing /mirror-builder
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'error'
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [53 lines of output]
      configuration error: `project.entry-points.fromager.project_overrides.nvidia-cutlass` must be python-entrypoint-reference
      DESCRIPTION:
          Reference to a Python object. It is either in the form
          ``importable.module``, or ``importable.module:object.attr``.
      
      GIVEN VALUE:
          "package_plugins.nvidia-cutlass"
      
      OFFENDING RULE: 'format'
      
      DEFINITION:
          {
              "type": "string",
              "format": "python-entrypoint-reference",
              "$comment": "https://packaging.python.org/specifications/entry-points/"
          }
      
      For more details about `format` see
      https://validate-pyproject.readthedocs.io/en/latest/api/validate_pyproject.formats.html

The failure is valid, as the hyphen in nvidia-cutlass is invalid for a package name.

Some useful links:

https://pypi.org/project/nvidia-cutlass/
https://github.com/NVIDIA/cutlass

**Comment by dhellmann** [comment]
This is why [pkgname_to_override_module](https://github.com/python-wheel-build/fromager/blob/main/src/fromager/overrides.py#L134) replaces hyphens with underscores.

**Comment by tiran** [comment]
For the record, hyphens are valid characters of a Python distribution name. See https://packaging.python.org/en/latest/specifications/name-normalization/ for naming normalization rules. There are additional special cases for legacy packages on PyPI.

However hyphans are not valid characters for an importable Python module. That's why you have to use `nvidia_cutlass` for the entry point and Python module. The [pkgname_to_override_module](https://github.com/python-wheel-build/fromager/blob/main/src/fromager/overrides.py#L134) function first turns the name into a canonical Python distribution name, then into a valid Python importable name.

**Comment by dhellmann** [comment]
@prarit Is this still an issue? If so, it's not clear what the next steps are.

**Comment by dhellmann** [comment]
I think this is not a bug. Please re-open if I'm wrong.
