### ISSUE TITLE
remove `example_override.py`

### ISSUE THREAD

**Issue by shubhbapna** [python-wheel-build/fromager#324]
Can we remove `example_override.py` and https://github.com/python-wheel-build/fromager/blob/main/pyproject.toml#L46 ?

I don't think we are testing overrides on fromager itself. The e2e tests seem to be using flit core

**Comment by dhellmann** [comment]
At one point there was a unit test to verify that the plugins loaded properly, but that flit-core e2e test is sufficient for that.
