### ISSUE TITLE
Include ELF requirements and provides in dist-info

### ISSUE THREAD

**Issue by tiran** [python-wheel-build/fromager#338]
The new feature `add_extra_metadata_to_wheels` allows us to add additional metadata files to wheel's dist-info. Let's add ELF provides and ELF requires information. The functionality of `analyze_wheel_elfdeps` should be moved into the `add_extra_metadata_to_wheels`  function, too. `analyze_wheel_elfdeps` needs to unpack the wheel zip file.

Should we store the information in a single TOML file or two simple text files?

**Comment by dhellmann** [comment]
I like separate text files.
