### ISSUE TITLE
incorrect req type for certain packages in build order

### ISSUE THREAD

**Issue by shubhbapna** [python-wheel-build/fromager#356]
Downstream when we bootstrap we get 3 different install versions of `numpy`: 1.26.4, 2.0.0, 2.1.0 and bootstrap ends up choosing `1.26.4` as the install dependency in the constraints file it generates. However, in the build order file `1.26.4` appears as a build-system requirement and `2.1.0` appears as an install requirement

**Comment by shubhbapna** [comment]
req type is not that relevant in the build order file so we can simply remove it

**Comment by dhellmann** [comment]
We could remove both the type and the why fields.

**Comment by shubhbapna** [comment]
why was removed in #313 (fromager 0.28+)
