### ISSUE TITLE
decouple downloading functions from resolution functions

### ISSUE THREAD

**Issue by shubhbapna** [python-wheel-build/fromager#368]
- [x] decouple wheel resolution and downloading #380 
- [x] decouple source resolution and downloading #384

**Comment by shubhbapna** [comment]
@dhellmann I am trying to decouple resolver_dist from download_source, but I have realized that because of the coupling download_source override allows user to skip the resolving part if they need to. If I decouple them, then fromager might try to resolve a package and cause a failure for some of our downstream packages.

Apart from redesigning the entire plugin, I only see one solution:
Add a check before resolving to see if there is an override for download source. Only call resolver_dist if there is no override (we don't end up completely decoupling them because we still need to check if there is a plugin for download_source)

Do you have any suggestions?

**Comment by dhellmann** [comment]
> @dhellmann I am trying to decouple resolver_dist from download_source, but I have realized that because of the coupling download_source override allows user to skip the resolving part if they need to. If I decouple them, then fromager might try to resolve a package and cause a failure for some of our downstream packages.
> 
> Apart from redesigning the entire plugin, I only see one solution: Add a check before resolving to see if there is an override for download source. Only call resolver_dist if there is no override (we don't end up completely decoupling them because we still need to check if there is a plugin for download_source)
> 
> Do you have any suggestions?

We could look to see if there's an override, and if that override takes the new version argument. That way existing overrides can continue to work as-is. That doesn't solve the problem of what to do when we update those overrides to take the new arg, though.

We have an override to give us a resolver provider. Is that sufficient, or do we need a higher level override for the resolution process entirely? For example, could we force the version of a package to 1 known good value from the override using our existing API?

**Comment by shubhbapna** [comment]
> For example, could we force the version of a package to 1 known good value from the override using our existing API?

We usually just do that directly in `download_source` override

**Comment by shubhbapna** [comment]
Summary of our discussion:

There is no way around, but to break the `download_source` plugin. We will introduce a new resolver_dist override that will return a Version object and url for a package. We will change the `download_source` plugin to take only this version object and url and return just the filename of the downloaded source
