### ISSUE TITLE
add time measurements for all steps in bootstrapping and build-sequence

### ISSUE THREAD

**Issue by shubhbapna** [python-wheel-build/fromager#408]
Right now we only measure the amount of time taken to build a wheel, we should also measure time for other steps during bootstrapping and build-sequence to help us detect performance bottlenecks. Maybe we should also measure other performance counters like memory usage?

**Comment by shubhbapna** [comment]
This could be interesting to get the actual memory usage when building a wheel: https://docs.python.org/3/library/resource.html#resource-usage

**Comment by dhellmann** [comment]
It would be good to produce some aggregate info at the end of the run, too. "bootstrapping took X time, Y in building wheels, Z in building sdists, etc." for whatever we collect.

**Comment by shubhbapna** [comment]
using cgroups might be a better way because it will let us track any child processes spawned
