### ISSUE TITLE
Validate names of package settings and patch directories

### ISSUE THREAD

**Issue by tiran** [python-wheel-build/fromager#410]
Fromager should ensure that settings files and patches directory use the override module name `canonicalize_name(name).replace("-", "_")`. In downstream we have a mix of canonical name and override module name for patches.

**Comment by dhellmann** [comment]
Based on https://github.com/python-wheel-build/fromager/blob/main/src/fromager/packagesettings.py#L474 I think we are already enforcing that naming convention, we just don't report issues with patches that don't match. #420 should help with that.

**Comment by dhellmann** [comment]
I think this was done with https://github.com/python-wheel-build/fromager/pull/424
