### ISSUE TITLE
Doc: Document output directories created by fromager 

### ISSUE THREAD

**Issue by rd4398** [python-wheel-build/fromager#411]
We need to document the output directories created by fromager

**Comment by rd4398** [comment]
@dhellmann I have a few questions:

- Do we create a separate .`md ` file for this like we did for input/output files?
- Just to confirm, we want to write about: `sdists-repo`, 'wheels-repo` and `work-dir` right?
- How much detailed information do we want? Is short description okay? Do we want to include sub-directory structure as well?

**Comment by dhellmann** [comment]
> @dhellmann I have a few questions:
> 
> * Do we create a separate .`md ` file for this like we did for input/output files?

The `files.md` page has the title "Input and Output files", so maybe the new info can go there?

> * Just to confirm, we want to write about: `sdists-repo`, 'wheels-repo`and`work-dir` right?

All of the output directories and their subdirectories. Look at the output from a simple bootstrap to see what you get.

> * How much detailed information do we want? Is short description okay? Do we want to include sub-directory structure as well?

Yes, subdirectories. It would be good to know what sorts of files are written to each directory, what files we write, etc. Everything the user needs to understand what we're doing and what information we're generating.
