### ISSUE TITLE
create per build log file before post build hook

### ISSUE THREAD

**Issue by shubhbapna** [python-wheel-build/fromager#447]
We use the post build hook to collect all the artifacts related to the build including log files. However, the per build log file is only ready after the post build hook: https://github.com/python-wheel-build/fromager/blob/main/src/fromager/commands/build.py#L196

**Comment by rd4398** [comment]
Okay, do I add the log file here in the hook as well?

```
hooks.run_post_build_hooks(
        ctx=wkctx,
        req=req,
        dist_name=canonicalize_name(req.name),
        dist_version=str(resolved_version),
        sdist_filename=sdist_filename,
        wheel_filename=wheel_filename,
       log_file=wheel_log
    )
```

**Comment by shubhbapna** [comment]
Nope that will break the API. You just need to move these lines before you call the `run_post_build_hooks`:
```
    per_wheel_logger.removeHandler(file_handler)
    file_handler.close()

    new_filename = wheel_log.with_name(wheel_filename.stem + ".log")
    wheel_log.rename(new_filename)
```

**Comment by rd4398** [comment]
okay!
