### ISSUE TITLE
Add a flag that downloads all the wheels from the given index instead of using `download-sequence`

### ISSUE THREAD

**Issue by shubhbapna** [python-wheel-build/fromager#450]
Advantages over `download-sequence`:
- we only download things as and when needed
- don't need the user to be worries about whether `download-sequence` is downloading the wheels at the right place
- we can download the wheel before we even download the source to enable #449

**Comment by dhellmann** [comment]
It might make more sense to use an existing mirroring tool, rather than adding this to fromager itself. https://packaging.python.org/en/latest/guides/index-mirrors-and-caches/ has a list of a few such tools we could look at.

**Comment by shubhbapna** [comment]
We don't really need a full pypi like mirror, I think we can get away with something simpler. Essentially, the user just gives us the base url of their private pypi index and we just check whether a package of some exact version is there in it or not. If it is there then we download it (not install it using pip) to extract the *-requirements.txt file that fromager had put in there

**Comment by dhellmann** [comment]
We have logic like that already, but it assumes the index is being updated by the bootstrap or build process. It sounds like you're saying we would run a local index, and if they give us a remote index we would look there for something that isn't already mirrored? And we would do that one wheel at a time, instead of pre-populating the index with all of the wheels at one time?

**Comment by shubhbapna** [comment]
> And we would do that one wheel at a time, instead of pre-populating the index with all of the wheels at one time?
 Yep. There are a couple of benefits of that:
- We don't have to assume that user correctly ran download-sequence to prepopulate the index
- As the list of wheels gets bigger, download sequence will take more and more time
- Using wheels as and when needed will allow us to do some prefetching which will hide the latency of prepopulating our index (later improvement on top of this)
