### ISSUE TITLE
Default values for template env vars

### ISSUE THREAD

**Issue by tiran** [python-wheel-build/fromager#461]
Extra environment variables support simple templating. We purposely did not implement extended variable expansion like `${VAR:-default}` or shell expression `$(process)`. The template values are coming from `os.environ` and previous environment lines.

Sometimes we want to extend a value, but still take the defaults into account, e.g. `CMAKE_ARGS=-DFOO ${CMAKE_ARGS}`. This fails when `CMAKE_ARGS` have not been defined before. In other cases it would be useful to have access to certain environment properties like the current CPU arch.

I'm suggesting to include C/C++ and CMAKE args, packaging default markers, and sysconfig settings in template envs. The values shall **not** be added to `extra_environ`! They are provided so extra environ values can use them for templating.

```python
import os
import sysconfig

from packaging import markers

template_env = {
    "CFLAGS": "",
    "CPPFLAGS": "",
    "CXXFLAGS": "",
    "LIBRARY_PATH": "",
    "C_INCLUDE_PATH": "",
    "CPLUS_INCLUDE_PATH": "",
    "CMAKE_ARGS": "",
    "CMAKE_LIBRARY_PATH": "",
    "CMAKE_INCLUDE_PATH": "",
    "sysconfig_platlib": sysconfig.get_path("platlib"),
    "sysconfig_purelib": sysconfig.get_path("purelib"),
}
template_env.update(**markers.default_environment())
# process env wins
template_env.update(os.environ)
```

### default vars

```json
{
  "CFLAGS": "",
  "CPPFLAGS": "",
  "CXXFLAGS": "",
  "LIBRARY_PATH": "",
  "C_INCLUDE_PATH": "",
  "CPLUS_INCLUDE_PATH": "",
  "CMAKE_ARGS": "",
  "CMAKE_LIBRARY_PATH": "",
  "CMAKE_INCLUDE_PATH": "",
  "sysconfig_platlib": ".../venv/lib64/python3.11/site-packages",
  "sysconfig_purelib": ".../venv/lib/python3.11/site-packages",
  "implementation_name": "cpython",
  "implementation_version": "3.11.9",
  "os_name": "posix",
  "platform_machine": "x86_64",
  "platform_release": "6.3.12-100.fc37.x86_64",
  "platform_system": "Linux",
  "platform_version": "#1 SMP PREEMPT_DYNAMIC Wed Jul  5 20:09:58 UTC 2023",
  "python_full_version": "3.11.9",
  "platform_python_implementation": "CPython",
  "python_version": "3.11",
  "sys_platform": "linux"
}
```

**Comment by dhellmann** [comment]
How likely is it for a user to want to set global defaults for any of those? I've lost track of whether that's possible today, or if they would have to specify values for each package separately. Maybe instead of hard-coding a list in fromager we make it easy to add values to the settings file?
