### ISSUE TITLE
Use bubblewrap (bwrap) instead of unshare for network isolation

### ISSUE THREAD

**Issue by tiran** [python-wheel-build/fromager#472]
Fromager implements network isolation with `unshare -rn`. The command creates a new network namespace without any interface and connection to the rest of the world. This works fine in most cases. However OpenMPI 4.x's compiler `mpicc` does not like our approach. It prints warnings to standard streams, which break's CMake's `FindMPI`.

One simple solution for the problem is [`bubblewrap`](https://github.com/containers/bubblewrap). The tool creates namespaces like `unshare` but with extra bells and whistles. `bwrap --unshare-net --dev-bind / /` unshares the network and creates a loopback interface in the new namespace. The `--dev-bind` is necessary to bind parent mounts into the new namespace and allow `/dev` access.

The tool is tiny (~ 100 kB) and available on all our target platforms.

**Comment by pnasrat** [comment]
I''m defintely in favor of bubblewrap will take a look at the PR

**Comment by shubhbapna** [comment]
`bwrap` didn't work for us as documented here https://github.com/python-wheel-build/fromager/pull/473#issuecomment-2412940902

we ended up using `unshare` with `ip link` see #477
