### ISSUE TITLE
Support variant specific patches

### ISSUE THREAD

**Issue by fabiendupont** [python-wheel-build/fromager#486]
When building wheels for different variants, the code base might be different from one variant to the other, for example when the code comes from a fork with variant specific features. And with a different code base, the patches may fail to be applied.

**Comment by tiran** [comment]
This is a very special case. I know only of three package that use custom forks for a variant: flash_attn, triton, and vllm. We are working towards unification of all the custom vendor forks. I expect that the forks will get merged into the baseline early next year.

I would prefer to solve the issue by either submitting the changes upstream or in the `prepare_source` hook of a downstream plugin.
