### ISSUE TITLE
validate whether downloaded wheel is valid or not

### ISSUE THREAD

**Issue by shubhbapna** [python-wheel-build/fromager#512]
In [_download_wheel_check](https://github.com/python-wheel-build/fromager/blob/main/src/fromager/wheels.py#L366) we currently just check whether the wheel file is a valid zip file. Lets instead check if it is a valid wheel file by using the `wheel.wheelfile.WheelFile` API as mentioned in https://github.com/python-wheel-build/fromager/issues/507#issuecomment-2492133631

**Comment by shubhbapna** [comment]
@tiran using `wheel.wheelfile.WheelFile(wheel_filename)` doesn't work. It throws an error says wheelfile is not an attribute of wheel

**Comment by tiran** [comment]
You have to import the submodule:

```python
>>> import wheel
>>> wheel.wheelfile.WheelFile
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'wheel' has no attribute 'wheelfile'
>>> import wheel.wheelfile
>>> wheel.wheelfile.WheelFile
<class 'wheel.wheelfile.WheelFile'>
```
