### ISSUE TITLE
Extract download source code from the build command

### ISSUE THREAD

**Issue by Gregory-Pereira** [python-wheel-build/fromager#78]
It would be helpful to separate the code for download source code out from the build command. From my understanding this will also be very helpful with regard to implementing #67 anyway.

**Comment by dhellmann** [comment]
Does `step download-source-archive` do what you need? https://github.com/python-wheel-build/fromager?tab=readme-ov-file#step-by-step-commands

**Comment by dhellmann** [comment]
> Yes! This implementation is actually ideal because it keeps a single entrypoint bootstrap as well as give access to the individual download source step. Appologies still getting familiar with the repo.

It's all part of the process. And I was honestly asking in case you had something different in mind and we needed to change the step command.
